import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import NextAuthProvider from "@/lib/auth/Provider";
import Navbar from "@/components/Navbar";
import TrpcProvider from "@/lib/trpc/Provider";
import Script from 'next/script';
import Header from '@/components/common/Header';
import { Knock } from '@knocklabs/node'
import { getUserAuth } from '@/lib/auth/utils';
import { redirect } from 'next/navigation';
import NotificationMenu from '@/components/nofication/NotificationMenu';



// const { userId, isLoading } = useIdentify();

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { session } = await getUserAuth();
  if (!session || !session?.user) {
    redirect('/api/auth/signin');
  }
  const knockClient = new Knock(process.env.NEXT_PUBLIC_KNOCK_SECRET_API_KEY);
  const knockUser = await knockClient.users.identify(session?.user?.id, {
    email: session?.user?.email,
    name: session?.user?.name,
  });

  const knockUserToken = Knock.signUserToken(session?.user?.id, {
    signingKey: process.env.NEXT_PUBLIC_KNOCK_SINGIN_KEY,
    expiresInSeconds: 60 * 60
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <NextAuthProvider>
            <TrpcProvider>
              <main className="container flex w-Device-breakpoint-Desktop min-w-Desktop max-w-1920 flex-col items-center bg-background-backgroundfull justify-center h-full">
                <Header />
                <NotificationMenu knockToken={knockUserToken} />
                {/* <Navbar /> */}
                {children}
              </main>
            </TrpcProvider>
          </NextAuthProvider>
          <Toaster />
        </ThemeProvider>
      </body>
      <head>
        <Script src="https://js.pusher.com/8.2.0/pusher.min.js" strategy="lazyOnload" />

      </head>
    </html>
  )
}
