import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import NextAuthProvider from "@/lib/auth/Provider";
import Navbar from "@/components/Navbar";
import TrpcProvider from "@/lib/trpc/Provider";
import Script from 'next/script';
import Header from '@/components/common/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <NextAuthProvider>
            <TrpcProvider>
              <main className="container flex w-Device-breakpoint-Desktop min-w-Desktop max-w-1920 flex-col items-center bg-background-backgroundfull justify-center h-full">
                <Header />

                {/* <Navbar /> */}
                {children}
              </main>
            </TrpcProvider>
          </NextAuthProvider>
          <Toaster />
        </ThemeProvider>
      </body>
      <head>
        <Script src="https://js.pusher.com/8.2.0/pusher.min.js" strategy="lazyOnload" />

      </head>
    </html>
  )
}
